### ISSUE TITLE
minimize window back to normal size

### ISSUE THREAD

**Issue by scientist1642** [ztomer/ZoneTilerWM#1]
Hey Tomer, I wonder if there is an api to minimize window back to where it was after hs.maximizeWindow.

Thanks.

**Comment by ztomer** [comment]
I'm not sure about an API, but you can save a vector of windows names-->{state, position}, and listen of window minimize events.

This guy implemented undo, maybe it got something relevant
https://github.com/songchenwen/dotfiles/tree/master/hammerspoon

**Comment by scientist1642** [comment]
Thank you! It was easy to add undo(which I only use for minimizing at the moment) from that file to your configuration. :surfer:
